// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFYyKj4wu3-H4aPphFIkDx9orqCZzNkaI',
    appId: '1:658258132797:web:6c1ba01d195430429a0f54',
    messagingSenderId: '658258132797',
    projectId: 'mitch-koko-88d9f',
    authDomain: 'mitch-koko-88d9f.firebaseapp.com',
    storageBucket: 'mitch-koko-88d9f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTFwe6VxzCCI0QwCyfuWxnvShq1nTFOek',
    appId: '1:658258132797:android:f5e9b02e4a737e789a0f54',
    messagingSenderId: '658258132797',
    projectId: 'mitch-koko-88d9f',
    storageBucket: 'mitch-koko-88d9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvTgfX2jRPsTUesNHj14bRSmEoOwIgB2w',
    appId: '1:658258132797:ios:9175d06f63d94a3c9a0f54',
    messagingSenderId: '658258132797',
    projectId: 'mitch-koko-88d9f',
    storageBucket: 'mitch-koko-88d9f.appspot.com',
    iosBundleId: 'com.example.minimalLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvTgfX2jRPsTUesNHj14bRSmEoOwIgB2w',
    appId: '1:658258132797:ios:9175d06f63d94a3c9a0f54',
    messagingSenderId: '658258132797',
    projectId: 'mitch-koko-88d9f',
    storageBucket: 'mitch-koko-88d9f.appspot.com',
    iosBundleId: 'com.example.minimalLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFYyKj4wu3-H4aPphFIkDx9orqCZzNkaI',
    appId: '1:658258132797:web:2e461bdd8bffde589a0f54',
    messagingSenderId: '658258132797',
    projectId: 'mitch-koko-88d9f',
    authDomain: 'mitch-koko-88d9f.firebaseapp.com',
    storageBucket: 'mitch-koko-88d9f.appspot.com',
  );
}
